apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-system

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: backend-api
  app.kubernetes.io/part-of: microservices-platform
  app.kubernetes.io/managed-by: argocd

configMapGenerator:
  - name: backend-config
    behavior: merge
    literals:
      - ENVIRONMENT=base

images:
  - name: my-registry/backend-api
    newTag: 1.0.0
