apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-system

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: frontend
  app.kubernetes.io/part-of: microservices-platform
  app.kubernetes.io/managed-by: argocd

configMapGenerator:
  - name: frontend-config
    behavior: merge
    literals:
      - ENVIRONMENT=base
      - API_TIMEOUT=30000

images:
  - name: my-registry/frontend
    newTag: 1.0.0
